SELECT CLIENT.NAME AS NAME,
       (MAX(EXTRACT (YEAR FROM AGE(PROJECT.FINISH_DATE, PROJECT.START_DATE)) * 12 +
            EXTRACT (MONTH FROM AGE(PROJECT.FINISH_DATE, PROJECT.START_DATE))))
                   AS MONTH
FROM CLIENT
         JOIN PROJECT ON PROJECT.CLIENT_ID = CLIENT.ID
GROUP BY CLIENT.NAME, PROJECT.START_DATE, PROJECT.FINISH_DATE
HAVING MAX(EXTRACT (YEAR FROM AGE(PROJECT.FINISH_DATE, PROJECT.START_DATE)) * 12 +
           EXTRACT (MONTH FROM AGE(PROJECT.FINISH_DATE, PROJECT.START_DATE)))
           IN (SELECT MAX(EXTRACT (YEAR FROM AGE(PROJECT.FINISH_DATE, PROJECT.START_DATE)) * 12 +
                          EXTRACT (MONTH FROM AGE(PROJECT.FINISH_DATE, PROJECT.START_DATE))) FROM PROJECT);