SELECT NAME, COUNT(CLIENT_ID) AS PROJECT_COUNT
FROM CLIENT
JOIN PROJECT ON CLIENT_ID = CLIENT.ID
GROUP BY NAME
HAVING COUNT(CLIENT_ID) = (SELECT MAX(MYCOUNT)
FROM (SELECT CLIENT_ID, COUNT(CLIENT_ID) MYCOUNT
FROM PROJECT GROUP BY CLIENT_ID));