SELECT CLIENT.NAME AS NAME, PROJECT.ID AS PROJECT,
       ((EXTRACT (YEAR FROM AGE(PROJECT.FINISH_DATE, PROJECT.START_DATE)) * 12 +
         EXTRACT (MONTH FROM AGE(PROJECT.FINISH_DATE, PROJECT.START_DATE))) *
        SUM(WORKER.SALARY))
                   AS PRICE
FROM CLIENT
         JOIN PROJECT ON PROJECT.CLIENT_ID = CLIENT.ID
         JOIN PROJECT_WORKER ON PROJECT_WORKER.PROJECT_ID = PROJECT.ID
         JOIN WORKER ON PROJECT_WORKER.WORKER_ID = WORKER.ID
GROUP BY CLIENT.NAME, PROJECT.ID;